-- ============================================================================
-- 202-MAKTAB — SEED (Phase 3 prototip kontent)
-- Qo'llash: Supabase Dashboard → SQL Editor → paste → Run
-- Idempotent: mavjud yozuvlar o'chirilmaydi/yozilmaydi (skip-existing).
-- MUHIM: jamoa, statistika va boshqa kontent — PROTOTIP ma'lumotlar.
-- Real School 202 kontenti Phase 5'da admin panel orqali kiritiladi.
-- ============================================================================

-- 1) Kategoriyalar
insert into news_categories (name, slug, sort_order) values ('Yangiliklar', 'yangiliklar', 0) on conflict (name) do nothing;
insert into news_categories (name, slug, sort_order) values ('Tadbirlar', 'tadbirlar', 1) on conflict (name) do nothing;
insert into news_categories (name, slug, sort_order) values ('Sport', 'sport', 2) on conflict (name) do nothing;
insert into news_categories (name, slug, sort_order) values ('Tanlovlar', 'tanlovlar', 3) on conflict (name) do nothing;
insert into news_categories (name, slug, sort_order) values ('Ochiq darslar', 'ochiq-darslar', 4) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Darslar', 'darslar', 0) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Sport', 'sport', 1) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Kutubxona', 'kutubxona', 2) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Tadbirlar', 'tadbirlar', 3) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Ijod', 'ijod', 4) on conflict (name) do nothing;
insert into gallery_categories (name, slug, sort_order) values ('Maktab muhiti', 'maktab-muhiti', 5) on conflict (name) do nothing;

-- 2) Sayt sozlamalari (singleton)
insert into site_settings (id, school_name, short_name, tagline, description, district, address, established, locale, phone, mobile, email, working_hours, social_links)
values (1, '202-maktab', '202-maktab', 'Bilim, tarbiya va kelajak bir maskanda.', '202-sonli umumiy o‘rta ta’lim maktabi', 'Toshkent shahri • Chilonzor tumani', 'Chilonzor tumani, Toshkent shahri, O‘zbekiston', '19XX', 'uz', '{"display":"+998 (71) 000-00-00","href":"tel:+998710000000"}'::jsonb, '{"display":"+998 (90) 000-00-00","href":"tel:+998900000000"}'::jsonb, '{"display":"info@202-maktab.uz","href":"mailto:info@202-maktab.uz"}'::jsonb, '[{"days":"Dushanba – Shanba","time":"08:00 – 15:00"},{"days":"Yakshanba","time":"Dam olish kuni"}]'::jsonb, '{"telegram":"https://t.me/202maktab","instagram":"https://instagram.com/202maktab"}'::jsonb)
on conflict (id) do nothing;

-- 3) Aloqa ma'lumoti (singleton, PROTOTIP koordinata — Phase 5 tasdiqlaydi)
insert into contact_information (id, address, phone, mobile, email, working_hours, latitude, longitude, map_embed, map_route, map_view, is_verified, social_links)
values (1, 'Chilonzor tumani, Toshkent shahri, O‘zbekiston', '{"display":"+998 (71) 000-00-00","href":"tel:+998710000000"}'::jsonb, '{"display":"+998 (90) 000-00-00","href":"tel:+998900000000"}'::jsonb, '{"display":"info@202-maktab.uz","href":"mailto:info@202-maktab.uz"}'::jsonb, '[{"days":"Dushanba – Shanba","time":"08:00 – 15:00"},{"days":"Yakshanba","time":"Dam olish kuni"}]'::jsonb, 41.2797, 69.2404, 'https://www.openstreetmap.org/export/embed.html?bbox=69.2054%2C41.2597%2C69.2754%2C41.2997&layer=mapnik&marker=41.2797%2C69.2404', 'https://www.google.com/maps/search/?api=1&query=41.2797%2C69.2404', 'https://www.openstreetmap.org/?mlat=41.2797&mlon=69.2404#map=15/41.2797/69.2404', false, '{"telegram":"https://t.me/202maktab","instagram":"https://instagram.com/202maktab"}'::jsonb)
on conflict (id) do nothing;

-- 4) Statistika (PROTOTIP qiymatlar)
insert into statistics (id, label, value, suffix, description, icon, sort_order, is_visible) values ('students', 'O‘quvchi', 1300, '+', '1–11-sinflarda tahsil olayotgan bolalar', 'users', 0, true) on conflict (id) do nothing;
insert into statistics (id, label, value, suffix, description, icon, sort_order, is_visible) values ('capacity', 'Loyiha quvvati', 1050, '', 'Binoning bir smenada o‘zlashtira oladigan o‘rin soni', 'building', 1, true) on conflict (id) do nothing;
insert into statistics (id, label, value, suffix, description, icon, sort_order, is_visible) values ('staff', 'Jamoa a’zolari', 92, '+', 'Ustozlar, murabbiylar va ma’muriyat', 'teacher', 2, true) on conflict (id) do nothing;
insert into statistics (id, label, value, suffix, description, icon, sort_order, is_visible) values ('inclusive', 'Inklyuziv ta’limdagi o‘quvchilar', 11, '+', 'Maxsus ehtiyojli bolalar uchun qo‘llab-quvvatlash tizimi', 'heart', 3, true) on conflict (id) do nothing;

-- 5) Imkoniyatlar (Ta'lim plitalari)
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('quality', '01', 'Sifatli ta’lim', 'Davlat standartiga asoslangan, ammo har bir o‘quvchining qiziqishi va temposiga moslashadigan dars tizimi.', 'book', null, null, 0, true) on conflict (id) do nothing;
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('classrooms', '02', 'Zamonaviy sinfxonalar', 'Yorug‘, shinam sinfxonalar, interaktiv uskunalar va fan kabinetlari — qulay muhitda chuqur o‘zlashtirish uchun.', 'monitor', '/images/edu-classroom.jpg', 'Zamonaviy sinfxona interyeri', 1, true) on conflict (id) do nothing;
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('sport', '03', 'Sport va rivojlanish', 'Sport zali, ochiq maydon va to‘garaklar — sog‘lom tanada sog‘lom aql tamoyili asosida jismoniy tarbiya.', 'ball', '/images/edu-sport.jpg', 'Maktab sport zali', 2, true) on conflict (id) do nothing;
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('library', '04', 'Kutubxona', 'O‘quv adabiyotlari, badiiy kitoblar va o‘quv zallari — mustaqil o‘qish va tadqiqot ko‘nikmalarini shakllantirish uchun.', 'library', '/images/edu-library.jpg', 'Maktab kutubxonasi', 3, true) on conflict (id) do nothing;
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('inclusive', '05', 'Inklyuziv ta’lim', 'Maxsus ehtiyojli o‘quvchilar uchun moslashtirilgan dasturlar, resurslar va malakali mutaxassislar yordami.', 'heart', '/images/edu-inclusive.jpg', 'Inklyuziv ta''lim xonasi', 4, true) on conflict (id) do nothing;
insert into features (id, display_index, title, description, icon, image_url, alt, sort_order, is_visible) values ('events', '06', 'Tadbirlar va maktab hayoti', 'Bayramlar, tanlovlar, olimpiadalar va ijodiy kechalar — o‘quvchilar o‘z qobiliyatlarini namoyish etadigan maydon.', 'star', '/images/edu-events.jpg', 'Maktab akt zali', 5, true) on conflict (id) do nothing;

-- 6) Inshootlar (scroll-hikoya)
insert into facilities (id, kicker, title, description, image_url, image_alt, sort_order, is_visible) values ('classrooms', '01 — O‘quv xonalari', 'Yorug‘ sinfxonalar', 'Katta oynalar, qulay mebel va interaktiv taxtalar — darsda e’tibor uzoq saqlanadigan muhit. Har bir kabinet fan talabiga mos jihozlangan.', '/images/edu-classroom.jpg', 'Yorug‘ zamonaviy sinfxona', 0, true) on conflict (id) do nothing;
insert into facilities (id, kicker, title, description, image_url, image_alt, sort_order, is_visible) values ('sport-hall', '02 — Sport inshooti', 'Sport zali va maydon', 'Voleybol va basketbol uchun jihozlangan zal, ochiq futbol maydoni va jismoniy tarbiya to‘garaklari — har kuni faol harakat uchun sharoit.', '/images/edu-sport.jpg', 'Sport zali', 1, true) on conflict (id) do nothing;
insert into facilities (id, kicker, title, description, image_url, image_alt, sort_order, is_visible) values ('assembly', '03 — Akt zali', 'Katta sahna zali', 'Bayramlar, anjumanlar va ijodiy kechalar o‘tkaziladigan keng zal. O‘quvchilar sahnada o‘zini erkin his qiladi va jamoa oldida gapirishni o‘rganadi.', '/images/edu-events.jpg', 'Akt zali', 2, true) on conflict (id) do nothing;
insert into facilities (id, kicker, title, description, image_url, image_alt, sort_order, is_visible) values ('library', '04 — Kutubxona', 'O‘quv va kitob zallari', 'Darsliklar, badiiy adabiyot va o‘quvchilar uchun tinch o‘qish burchaklari. Mustaqil ta’lim olish uchun birinchi manzil.', '/images/edu-library.jpg', 'Kutubxona zali', 3, true) on conflict (id) do nothing;
insert into facilities (id, kicker, title, description, image_url, image_alt, sort_order, is_visible) values ('inclusive-rooms', '05 — Inklyuziv xonalar', 'Qo‘llab-quvvatlash xonalari', 'Maxsus ehtiyojli o‘quvchilar bilan individual va kichik guruhlarda ishlash uchun moslashtirilgan, tinch va mehribon muhit.', '/images/edu-inclusive.jpg', 'Inklyuziv ta''lim xonasi', 4, true) on conflict (id) do nothing;

-- 7) Jamoa (PROTOTIP ismlar — hech qachon real deb taqdim etilmaydi)
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-01', 'Aziza Karimova', 'Maktab direktori', null, 'Rahbariyat', 'leadership', '24 yil tajriba', '/images/people/p-01.jpg', 'Maktab direktori — prototip portret', 0, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-02', 'Rustam Abdullayev', 'Direktor o‘rinbosari — o‘quv ishlari', null, 'Rahbariyat', 'leadership', '19 yil tajriba', '/images/people/p-02.jpg', 'O‘quv ishlari bo‘yicha direktor o‘rinbosari — prototip portret', 1, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-03', 'Dilnoza Rahimova', 'Direktor o‘rinbosari — tarbiya ishlari', null, 'Rahbariyat', 'leadership', '16 yil tajriba', '/images/people/p-03.jpg', 'Tarbiya ishlari bo‘yicha direktor o‘rinbosari — prototip portret', 2, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-04', 'Jasur To‘xtayev', 'Matematika fani o‘qituvchisi', 'Matematika', 'Aniq fanlar', 'teachers', '14 yil tajriba', '/images/people/p-04.jpg', 'Matematika fani o‘qituvchisi — prototip portret', 3, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-05', 'Kamola Yusupova', 'Boshlang‘ich sinf o‘qituvchisi', 'Boshlang‘ich sinf', 'Boshlang‘ich sinf', 'teachers', '11 yil tajriba', '/images/people/p-05.jpg', 'Boshlang‘ich sinf o‘qituvchisi — prototip portret', 4, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-06', 'Sardor Nazarov', 'Fizika va astronomiya o‘qituvchisi', 'Fizika', 'Aniq fanlar', 'teachers', '9 yil tajriba', '/images/people/p-06.jpg', 'Fizika fani o‘qituvchisi — prototip portret', 5, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-07', 'Nilufar Saidova', 'Ona tili va adabiyot o‘qituvchisi', 'Ona tili', 'Til fanlari', 'teachers', '17 yil tajriba', null, '', 6, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-08', 'Bekzod Ergashev', 'Ingliz tili o‘qituvchisi', 'Ingliz tili', 'Til fanlari', 'teachers', '8 yil tajriba', null, '', 7, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-09', 'Gulnora Ismoilova', 'Kimyo biologiya o‘qituvchisi', 'Biologiya', 'Aniq fanlar', 'teachers', '21 yil tajriba', null, '', 8, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-10', 'Otabek Xolmatov', 'Jismoniy tarbiya ustasi', 'Jismoniy tarbiya', 'San’at va jismoniy tarbiya', 'teachers', '12 yil tajriba', null, '', 9, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-11', 'Malika Tursunova', 'Informatika o‘qituvchisi', 'Informatika', 'Aniq fanlar', 'teachers', '7 yil tajriba', null, '', 10, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-12', 'Zulfiya Norova', 'Tarix o‘qituvchisi', 'Tarix', 'Til fanlari', 'teachers', '15 yil tajriba', null, '', 11, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-13', 'Feruza Aliyeva', 'Inklyuziv ta’lim murabbiyi', 'Maxsus pedagogika', 'Boshlang‘ich sinf', 'teachers', '10 yil tajriba', null, '', 12, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-14', 'Shahzod Umarov', 'San’at va tasviriy to‘garak rahbari', 'Tasviriy san’at', 'San’at va jismoniy tarbiya', 'teachers', '6 yil tajriba', null, '', 13, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-15', 'Xurshida Qodirova', 'O‘quv bo‘limi mudirasi', null, 'Ma’muriyat', 'administration', '18 yil tajriba', null, '', 14, true) on conflict (id) do nothing;
insert into team_members (id, full_name, position, subject, category, member_group, experience, photo_url, photo_alt, sort_order, is_visible) values ('p-16', 'Alisher Yo‘ldoshev', 'Ijtimoiy psixolog', null, 'Ma’muriyat', 'administration', '9 yil tajriba', null, '', 15, true) on conflict (id) do nothing;

-- 8) Galereya (PROTOTIP media)
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-01', 'image', '/images/hero.jpg', null, 'Maktab binosi tashqaridan', 'Maktab muhiti', (select id from gallery_categories where name = 'Maktab muhiti'), 'Binolar', 1792, 1008, 0, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-02', 'image', '/images/intro.jpg', null, 'Maktab koridori', 'Maktab muhiti', (select id from gallery_categories where name = 'Maktab muhiti'), 'Binolar', 1024, 1280, 1, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-03', 'image', '/images/edu-classroom.jpg', null, 'Zamonaviy sinfxona', 'Darslar', (select id from gallery_categories where name = 'Darslar'), 'Sinfxonalar', 1024, 768, 2, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-04', 'image', '/images/edu-quality.jpg', null, 'Dars jarayoni', 'Darslar', (select id from gallery_categories where name = 'Darslar'), 'Sinfxonalar', 1536, 1024, 3, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-05', 'image', '/images/edu-sport.jpg', null, 'Sport zali', 'Sport', (select id from gallery_categories where name = 'Sport'), 'Sport', 1536, 1024, 4, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-06', 'image', '/images/life-sport.jpg', null, 'Ochiq maydonda futbol', 'Sport', (select id from gallery_categories where name = 'Sport'), 'Sport', 1536, 1024, 5, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-07', 'image', '/images/edu-library.jpg', null, 'Kutubxona', 'Kutubxona', (select id from gallery_categories where name = 'Kutubxona'), 'Kutubxona', 1536, 1024, 6, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-08', 'image', '/images/edu-events.jpg', null, 'Akt zali', 'Tadbirlar', (select id from gallery_categories where name = 'Tadbirlar'), 'Tadbirlar', 1792, 1008, 7, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-09', 'image', '/images/life-ijod.jpg', null, 'Ijodiy to‘garak', 'Ijod', (select id from gallery_categories where name = 'Ijod'), 'Ijod', 1536, 1024, 8, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-10', 'image', '/images/edu-inclusive.jpg', null, 'Inklyuziv ta’lim xonasi', 'Darslar', (select id from gallery_categories where name = 'Darslar'), 'Sinfxonalar', 1024, 768, 9, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('g-11', 'image', '/images/life-muhit.jpg', null, 'Yashil maktab hovlisi', 'Maktab muhiti', (select id from gallery_categories where name = 'Maktab muhiti'), 'Hovli', 1024, 1280, 10, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('v-01', 'video', '/video/campus.mp4', '/images/hero.jpg', 'Maktab binosi video lavhasi', 'Maktab muhiti', (select id from gallery_categories where name = 'Maktab muhiti'), 'Video', 1792, 1008, 11, true) on conflict (id) do nothing;
insert into gallery_items (id, type, src, poster, alt, category, category_id, album, width, height, sort_order, is_visible) values ('v-02', 'video', '/video/sport.mp4', '/images/life-sport.jpg', 'Sport maydoni video lavhasi', 'Sport', (select id from gallery_categories where name = 'Sport'), 'Video', 1792, 1008, 12, true) on conflict (id) do nothing;

-- 9) Tez havolalar
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('parents', 'Ota-onalar uchun', 'Uchrashuvlar, maslahatlar va maktab hayotidagi o‘ringiz', 'users', '/contact#faq', false, 0, true) on conflict (id) do nothing;
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('students', 'O‘quvchilar uchun', 'To‘garaklar, olimpiadalar va foydali resurslar', 'graduation', '/education#activities', false, 1, true) on conflict (id) do nothing;
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('admission', 'Qabul haqida', 'Hujjatlar ro‘yxati va qabul jarayoni', 'clipboard', '/contact#form', false, 2, true) on conflict (id) do nothing;
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('schedule', 'Dars jadvali', 'Smenalar va dars soatlari bo‘yicha ma’lumot', 'calendar', '/education#stages', false, 3, true) on conflict (id) do nothing;
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('docs', 'Hujjatlar', 'Ustav, litsenziya va namunaviy hujjatlar', 'file', '/contact#map', false, 4, true) on conflict (id) do nothing;
insert into quick_links (id, title, description, icon, url, open_in_new_tab, sort_order, is_visible) values ('faq', 'Savol-javoblar', 'Eng ko‘p beriladigan savollarga javoblar', 'chat', '/contact#faq', false, 5, true) on conflict (id) do nothing;

-- 10) FAQ (unique constraint yo'q → WHERE NOT EXISTS idempotentlik uchun)
insert into faqs (question, answer, sort_order, is_visible) select 'Maktabga qanday qabul qilinadi?', 'Qabul har yili yoz oylarida o‘tkaziladi. Hujjatlar ro‘yxati, smena va sinf to‘ldirilganligi haqida aniq ma’lumotni maktab ma’muriyati yoki aloqa bo‘limidan olishingiz mumkin. Saytdagi aloqa formasi orqali ham murojaat qilishingiz mumkin.', 0, true where not exists (select 1 from faqs where question = 'Maktabga qanday qabul qilinadi?');
insert into faqs (question, answer, sort_order, is_visible) select 'Darslar nechchi smenada o‘tiladi?', 'Smenalar jadvali har o‘quv yilida sinflar soniga qarab shakllantiriladi. Aniq jadvalni sinf rahbari yoki maktab ma’muriyati beradi.', 1, true where not exists (select 1 from faqs where question = 'Darslar nechchi smenada o‘tiladi?');
insert into faqs (question, answer, sort_order, is_visible) select 'Maktabda to‘garaklar bormi?', 'Ha. Sport, ijod, til va texnik yo‘nalishdagi to‘garaklar faoliyat yuritadi. To‘garaklar ro‘yxati va qabul shartlari «Ta’lim» sahifasida e’lon qilinadi.', 2, true where not exists (select 1 from faqs where question = 'Maktabda to‘garaklar bormi?');
insert into faqs (question, answer, sort_order, is_visible) select 'Inklyuziv ta’lim qanday tashkil etilgan?', 'Maxsus ehtiyojli o‘quvchilar uchun moslashtirilgan dasturlar, qo‘llab-quvvatlash xonalari va malakali murabbiylar mavjud. Har bir holat individual o‘rganiladi.', 3, true where not exists (select 1 from faqs where question = 'Inklyuziv ta’lim qanday tashkil etilgan?');
insert into faqs (question, answer, sort_order, is_visible) select 'Ota-onalar maktab hayotida qanday qatnashadi?', 'Ota-onalar qo‘mitasi, ochiq eshiklar kunlari va muntazam uchrashuvlar orqali maktab hayotida faol ishtirok etadi. Barcha tadbirlar yangiliklar bo‘limida e’lon qilinadi.', 4, true where not exists (select 1 from faqs where question = 'Ota-onalar maktab hayotida qanday qatnashadi?');

-- 11) Yangiliklar (PROTOTIP tahririy matnlar, published)
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('yangi-oquv-yili-2026', 'Yangi o‘quv yili 2026–2027: birga katta maqsadlar sari', '1-sentabr — bilim bayrami. Bu yil maktabimizda yangi o‘quvchilar, yangi loyihalar va yangi imkoniyatlar bilan kutilmoqda.', '[{"type":"h","text":"Bayram tongi"},{"type":"p","text":"202-maktab hovlisida 1-sentabr tongi yana bir bor bilim bayramiga aylandi. Birinchi sinf o‘quvchilarini katta hurmat bilan kutib olishdik — ustozlar va katta o‘quvchilar ularni gulchambarlar bilan kutib oldi."},{"type":"quote","text":"Har bir o‘quv yili — yangi sahifa. Biz u sahifalarga birgalikda yozamiz."},{"type":"h","text":"Yangi loyihalar"},{"type":"p","text":"Yangi o‘quv yilida fan to‘garaklari, sport musobaqalari va ijodiy loyihalar yanada kengayadi. Ota-onalar uchun axborot uchrashuvlari jadvali maktab kanalida e’lon qilinadi."},{"type":"p","text":"Barcha o‘quvchi, ustoz va ota-onalarga sog‘lom, omadli va barakali o‘quv yili tilaymiz!"}]'::jsonb, '/images/hero.jpg', 'Maktab binosi bayram kuni', 'Yangiliklar', (select id from news_categories where name = 'Yangiliklar'), null, '3 daqiqa', true, '2026-09-01T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('ota-onalar-uchun-ochiq-eshiklar-kuni', 'Ota-onalar uchun ochiq eshiklar kuni', 'Sentabr oyi davomida ota-onalar maktabga tashrif buyurib, sinfxonalar bilan tanishishi va ustozlar bilan uchrashishi mumkin.', '[{"type":"p","text":"Ochiq eshiklar kuni — ota-onalar uchun maktab hayotini ichidan ko‘rish imkoniyati. Tashrif davomida sinfxonalar, sport zali va kutubxona bilan tanishasiz."},{"type":"p","text":"Aniq sana va vaqt maktab rasmiy kanallarida e’lon qilinadi. Keling, birgalikda o‘quvchilarimiz kelajagini quramiz."}]'::jsonb, '/images/news-open-door.jpg', 'Ota-onalar maktab koridorida', 'Tadbirlar', (select id from news_categories where name = 'Tadbirlar'), null, '2 daqiqa', true, '2026-09-18T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('fan-olimpiadalari-bosqichi', 'Fan olimpiadalarining tuman bosqichi boshlanmoqda', 'Matematika, fizika va ona tili fani olimpiadalari uchun maktab bosqichi yakunlandi. G‘oliblar tuman bosqichiga yo‘l oldi.', '[{"type":"p","text":"Maktab bosqichida yuzlab o‘quvchilar qatnashdi. Eng yaxshi natijalarni ko‘rsatgan o‘quvchilar tuman bosqichida maktabimiz sharafini himoya qiladi."},{"type":"quote","text":"Olimpiada — bu faqat musobaqa emas, bu intellektual bayram."},{"type":"p","text":"Barcha qatnashchilarga omad tilaymiz!"}]'::jsonb, '/images/news-olympiad.jpg', 'Olimpiada medallari', 'Tanlovlar', (select id from news_categories where name = 'Tanlovlar'), null, '2 daqiqa', true, '2026-09-24T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('robototexnika-togarak-qabul', 'Robototexnika va STEM to‘garaklariga qabul boshlandi', 'Boshlang‘ich va o‘rta sinf o‘quvchilari uchun yangi STEM to‘garaklari ochiladi. Joylar soni cheklangan.', '[{"type":"p","text":"STEM ta’limi — muhandislik va texnologiyaga qiziqqan bolalar uchun birinchi qadam. To‘garakda o‘quvchilar oddiy robotlar yasashni va dasturlash asoslarini o‘rganadi."},{"type":"p","text":"Ro‘yxatdan o‘tish uchun sinf rahbaringizga murojaat qiling."}]'::jsonb, '/images/news-stem.jpg', 'Robototexnika to''garagi jihozlari', 'Yangiliklar', (select id from news_categories where name = 'Yangiliklar'), null, '2 daqiqa', true, '2026-10-02T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('maktab-spogatki-yakuni', 'Maktab sporti: kuzgi spartakiada yakunlandi', 'Futbol, voleybol va shaxmat bo‘yicha sinflar o‘rtasidagi musobaqalar muhim natijalar bilan yakunlandi.', '[{"type":"p","text":"Kuzgi spartakiada ikki hafta davom etdi. Barcha sinflar faol qatnashdi — maydonda do‘stlik va kurash ruhi qaynadi."},{"type":"p","text":"G‘olib sinflar maktab qiroysida taqdirlandi. Barcha ishtirokchilarga rahmat!"}]'::jsonb, '/images/life-sport.jpg', 'Maktab maydonchasida futbol', 'Sport', (select id from news_categories where name = 'Sport'), null, '3 daqiqa', true, '2026-10-15T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;
insert into news_articles (slug, title, excerpt, content, cover_image, cover_alt, category, category_id, author_name, reading_time, is_published, published_at)
values ('ochiq-darslar-haftaligi', 'Ochiq darslar haftaligi: ustozlar tajribasi ulashmoqda', 'Maktabimizda ochiq darslar haftaligi o‘tkaziladi — ota-onalar va kollega ustozlar darslarni kuzatishi mumkin.', '[{"type":"p","text":"Ochiq darslar — pedagogik mahoratni oshirish va shaffoflik uchun muhim an’ana. Bu haftada bir nechta ustozlar darslarini ochiq o‘tadi."},{"type":"p","text":"Qatnashish uchun oldindan ro‘yxatdan o‘tish talab etiladi."}]'::jsonb, '/images/edu-quality.jpg', 'Ochiq dars jarayoni', 'Ochiq darslar', (select id from news_categories where name = 'Ochiq darslar'), null, '2 daqiqa', true, '2026-11-05T06:00:00Z'::timestamptz)
on conflict (slug) do nothing;

-- ============================================================================
-- TEKSHIRUV — quyidagi hisobot SQL Editor'da natija sifatida chiqadi:
-- ============================================================================
select 'jadval (public sxema)' as narsa, count(*)::text as soni from information_schema.tables where table_schema = 'public'
union all select 'site_settings', count(*)::text from site_settings
union all select 'contact_information', count(*)::text from contact_information
union all select 'news_categories', count(*)::text from news_categories
union all select 'gallery_categories', count(*)::text from gallery_categories
union all select 'statistics', count(*)::text from statistics
union all select 'features', count(*)::text from features
union all select 'facilities', count(*)::text from facilities
union all select 'team_members', count(*)::text from team_members
union all select 'gallery_items', count(*)::text from gallery_items
union all select 'quick_links', count(*)::text from quick_links
union all select 'faqs', count(*)::text from faqs
union all select 'news_articles (published)', count(*)::text from news_articles where is_published
union all select 'rls yoqilgan jadvallar', count(*)::text from pg_tables where schemaname = 'public' and rowsecurity
order by narsa;

